version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - run:
          command: |
          name: build frontend
          command: |
            cd frontend
            npm install
            npm run build

workflows:
  default:
    jobs:
      - build-frontend