version: 2.1

jobs:
  lint-frontend:
    environment:
      CODE: 123
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - run:
          name: lint frontend
          command: |
            cd frontend
            echo $code
            npm install
            npm run build

  test-frondend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
<<<<<<< HEAD
      - restore_cache:
          keys: ["frontend-build"]
      - run:
          name: Run frontend test
          command: |
            cd frontend
            npm install
            npm run test
          
  build-backend:
    environment:
      CODE: 123
=======
      - run:
          command: |
            cd frontend
            npm install

      - run:
          command: |
            cd frontend
            npm run build
  test-frondend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install

      - run:
          command: |
            cd frontend
            npm run test
  build-backend:
>>>>>>> 854bdef (Adding Give your Application Auto-Deploy Superpowers)
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
<<<<<<< HEAD
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - run:
          name: build backend
          command: |
            cd backendtend
            echo $code
            npm install
            npm run build

=======
      - run:
          command: |
            cd backend
            npm install

      - run:
          command: |
            cd backend
            npm run build
>>>>>>> 854bdef (Adding Give your Application Auto-Deploy Superpowers)
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
<<<<<<< HEAD
      - restore_cache:
          keys: ["backend-build"]
=======
>>>>>>> 854bdef (Adding Give your Application Auto-Deploy Superpowers)
      - run:
          command: |
            cd backend
            npm install
<<<<<<< HEAD
            npm run test

=======
      - run:
          command: |
            cd backend
            npm run test
>>>>>>> 854bdef (Adding Give your Application Auto-Deploy Superpowers)
  audit-check-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm audit fix --audit-level=critical --force
  audit-check-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm audit fix --audit-level=critical --force 
  create_infrastructure_backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name backend
  create_infrastructure_cloudfront:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure cloudfront infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name cloudfront  
  create_infrastructure_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure frontend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name frontend 
  create_infrastructure_network:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure network infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --stack-name network                           
workflows:
  default:
    jobs:
<<<<<<< HEAD
      - lint-frontend
=======
      - build-frontend
>>>>>>> 854bdef (Adding Give your Application Auto-Deploy Superpowers)
      - test-frondend:
          requires:
            - build-frontend
      - build-backend:
          requires:
            - test-frondend
      - test-backend:
          requires:
            - build-backend
      - audit-check-frontend:
          requires:
            - test-backend
      - audit-check-backend:
          requires:
            - audit-check-frontend
      - create_infrastructure_backend
      - create_infrastructure_cloudfront
      - create_infrastructure_frontend
      - create_infrastructure_network
